services:
  api:
    build:
      context: ./backend
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/backend"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:13.0-alpine
    env_file:
      - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT_HOST}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/frontend"

volumes:
  postgres_data:
