# fly.toml app configuration file generated for yoga-app-back on 2023-08-22T08:45:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yoga-app-back"
primary_region = "cdg"
console_command = "/code/manage.py shell"

[build]
dockerfile = "Dockerfile.flyio"

[deploy]
release_command = "python manage.py migrate"

[env]
PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[statics]]
guest_path = "/code/static"
url_prefix = "/static/"
