# Generated by Django 4.2.3 on 2023-08-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga", "0002_session_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="picture_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
