# Generated by Django 4.2.4 on 2023-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0005_booking_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', help_text='Status of the booking', max_length=20),
        ),
    ]
