# Generated by Django 4.2.4 on 2023-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_token_is_used_token_used_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('verification', 'Verification'), ('reset_password', 'Reset Password')], help_text='The type of the token', max_length=20),
        ),
    ]
